Change webpack-dev-server options as weird workaround for weird bug.
When I make certain seemingly innocuous code changes, I get
the error message

> ERROR in ./pkg/index_bg.wasm
> Module not found: Error: Can't resolve 'env' in '/Users/kpreid/Projects/all-is-cubes/all-is-cubes-wasm/pkg'

Advice for this error generally says "you have an unresolved import",
i.e. a function that isn't actually available in WASM. However, no
source has told me how to debug this further, and the kind of code
changes I've been making should not affect what external functions
are used (e.g. changing the presence of an #[inline] declaration).

Running `node_modules/.bin/webpack --display-error-details` does not
show anything other than the failed resolution of the "env" module —
which is another thing I don't understand, because there isn't any
"env" as far as I know in _successful_ builds. Maybe "env" is where
those missing imports are expected to be found?

While experimenting with different build options, I found that, even
though `webpack --help` claims that `-d` is an alias for
`--debug --devtool eval-cheap-module-source-map --output-pathinfo`,
the latter succeeds where the former fails. So, I'm changing to those
options with the hope that, whatever the difference, they're good enough
for my needs.